# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K1rhm8g73rHyFgibPiTef81wcC4NTcZY
"""

# Paso 1: Instalar las bibliotecas necesarias
# !pip install mediapipe opencv-python-headless==4.5.4.60

# Paso 2: Importar las bibliotecas
import cv2
import mediapipe as mp
from google.colab.patches import cv2_imshow  # Para mostrar imágenes en Colab

# Inicializar MediaPipe Hands y los componentes necesarios
mp_hands = mp.solutions.hands
mp_drawing = mp.solutions.drawing_utils

# Configuración del detector de manos
hands = mp_hands.Hands(static_image_mode=False,
                       max_num_hands=2,
                       min_detection_confidence=0.5,
                       min_tracking_confidence=0.5)

# Paso 3: Capturar un video o usar una imagen
# Nota: En Colab, no podemos acceder a la cámara directamente. Usa un video o una imagen estática.
# Sube un archivo de video primero en el panel de archivos de Colab
video_path = '/content/video.mp4'  # Cambia esto al nombre de tu archivo subido

# Cargar el video
cap = cv2.VideoCapture(video_path)

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        print("Fin del video o error al leer.")
        break

    # Convertir la imagen a RGB porque Mediapipe trabaja con este formato
    frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    # Procesar la imagen para detectar las manos
    result = hands.process(frame_rgb)

    # Dibujar las manos detectadas con sus landmarks
    if result.multi_hand_landmarks:
        for hand_landmarks in result.multi_hand_landmarks:
            mp_drawing.draw_landmarks(
                frame, hand_landmarks, mp_hands.HAND_CONNECTIONS,
                mp_drawing.DrawingSpec(color=(0, 255, 0), thickness=2, circle_radius=4),
                mp_drawing.DrawingSpec(color=(0, 0, 255), thickness=2, circle_radius=2)
            )

    # Mostrar el fotograma procesado (solo imágenes estáticas en Colab)
    cv2_imshow(frame)

# Liberar recursos
cap.release()